os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-penpot-exporter

script:
  - cd "$dir"
  # Test containers build
  - docker-compose -f docker-compose.test.yml build
  - docker images
  # Test containers run
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "penpot-exporter-db"
  - docker-compose -f docker-compose.test.yml ps "penpot-exporter-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "penpot-exporter"
  - docker-compose -f docker-compose.test.yml ps "penpot-exporter" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.test.yml down
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "penpot-exporter-db"
  - docker-compose -f docker-compose.test.yml ps "penpot-exporter-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "penpot-exporter"
  - docker-compose -f docker-compose.test.yml ps "penpot-exporter" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"

notifications:
  email: false

env: # Environments
    - VERSION=1.5 VARIANT=alpine
    - VERSION=1.5 VARIANT=buster-slim
    - VERSION=1.5 VARIANT=buster
    - VERSION=develop VARIANT=alpine
    - VERSION=develop VARIANT=buster-slim
    - VERSION=develop VARIANT=buster
    - VERSION=main VARIANT=alpine
    - VERSION=main VARIANT=buster-slim
    - VERSION=main VARIANT=buster
