#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

#echo 'Preparing persisted data...'
#mkdir -p "/srv/penpot-exporter/data"
#chown 777 "/srv/penpot-exporter/data"
